# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_organization_id',
            field=models.CharField(blank=True, help_text='The stripe connect Id used to group payments', max_length=250, null=True),
        ),
    ]
