# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20170527_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
