# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20170601_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
