# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20170601_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='voucher',
            name='coupon_code',
            field=models.CharField(default='XXXX-XXXX-XXXX-XXXX', max_length=19),
            preserve_default=False,
        ),
    ]
