# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20170603_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='uuid',
        ),
        migrations.AddField(
            model_name='voucher',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
