# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20170603_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='coupon_code',
            field=models.CharField(default=organizations.models.generate_coupon_code, editable=False, max_length=19),
        ),
    ]
