# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20170603_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expiration_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
