# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_offer_expiration_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
