# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20170615_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
